"""add_registration_requests_table

Revision ID: a1e404502aac
Revises: ce58bba5d461
Create Date: 2026-05-05 16:30:39.639351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1e404502aac'
down_revision: Union[str, Sequence[str], None] = 'ce58bba5d461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='registration_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('requested_by_ip', postgresql.INET(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index(op.f('idx_aggregated_data_dashboard_graph'), table_name='aggregated_data')
    op.drop_index(op.f('idx_aggregated_data_dashboard_id'), table_name='aggregated_data')
    op.drop_index(op.f('idx_aggregated_data_dims_gin'), table_name='aggregated_data', postgresql_using='gin')
    op.drop_index(op.f('idx_aggregated_data_graph_id'), table_name='aggregated_data')
    op.drop_index(op.f('idx_dashboard_access_dashboard'), table_name='dashboard_access')
    op.drop_index(op.f('idx_dashboard_access_user'), table_name='dashboard_access')
    op.create_index('idx_access_dashboard', 'dashboard_access', ['dashboard_id'], unique=False)
    op.create_index('idx_dashboard_filter', 'dashboard_filters', ['dashboard_id', 'filter_id'], unique=False)
    op.alter_column('dashboards', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_dashboards_name'), table_name='dashboards')
    op.create_unique_constraint(None, 'dashboards', ['name'])
    op.drop_column('dashboards', 'config')
    op.alter_column('filters', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_filters_name'), table_name='filters')
    op.create_unique_constraint(None, 'filters', ['name'])
    op.alter_column('graphs', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_graphs_dashboard'), table_name='graphs')
    op.drop_index(op.f('idx_graphs_dashboard_name'), table_name='graphs')
    op.create_unique_constraint('uq_graph_dashboard_name', 'graphs', ['dashboard_id', 'name'])
    op.alter_column('layouts', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_layouts_name'), table_name='layouts')
    op.create_unique_constraint(None, 'layouts', ['name'])
    op.alter_column('processing_logs', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('idx_processing_logs_dashboard_id'), table_name='processing_logs')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_role', table_name='users')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_processing_logs_dashboard_id'), 'processing_logs', ['dashboard_id'], unique=False)
    op.alter_column('processing_logs', 'message',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'layouts', type_='unique')
    op.create_index(op.f('idx_layouts_name'), 'layouts', ['name'], unique=True)
    op.alter_column('layouts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_graph_dashboard_name', 'graphs', type_='unique')
    op.create_index(op.f('idx_graphs_dashboard_name'), 'graphs', ['dashboard_id', 'name'], unique=True)
    op.create_index(op.f('idx_graphs_dashboard'), 'graphs', ['dashboard_id'], unique=False)
    op.alter_column('graphs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'filters', type_='unique')
    op.create_index(op.f('idx_filters_name'), 'filters', ['name'], unique=True)
    op.alter_column('filters', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('dashboards', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dashboards', type_='unique')
    op.create_index(op.f('idx_dashboards_name'), 'dashboards', ['name'], unique=True)
    op.alter_column('dashboards', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_dashboard_filter', table_name='dashboard_filters')
    op.drop_index('idx_access_dashboard', table_name='dashboard_access')
    op.create_index(op.f('idx_dashboard_access_user'), 'dashboard_access', ['user_id'], unique=False)
    op.create_index(op.f('idx_dashboard_access_dashboard'), 'dashboard_access', ['dashboard_id'], unique=False)
    op.create_index(op.f('idx_aggregated_data_graph_id'), 'aggregated_data', ['graph_id'], unique=False)
    op.create_index(op.f('idx_aggregated_data_dims_gin'), 'aggregated_data', ['dims'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_aggregated_data_dashboard_id'), 'aggregated_data', ['dashboard_id'], unique=False)
    op.create_index(op.f('idx_aggregated_data_dashboard_graph'), 'aggregated_data', ['dashboard_id', 'graph_id'], unique=False)
    op.drop_table('registration_requests')
    # ### end Alembic commands ###
